### ISSUE TITLE
[Epic] 2.2: Sharded capability discovery for light protocols

### ISSUE THREAD

**Issue by jm-clius** [waku-org/pm#63] opened 2023-09-01 15:14 UTC
**Epic label**: `E:2.2: Sharded cap discovery for light protocols`

# Summary

Ability to discover peers providing filter, lightpush and peer-exchange services within the decentralised network. To the application this should present as a peer selection mechanism that translates content topics to underlying shard.

# Acceptance Criteria

# Tasks

- [x] js-waku: https://github.com/waku-org/js-waku/issues/1506
- [x] go-waku: https://github.com/waku-org/go-waku/issues/839

**Comment by fryorcraken** [comment] 2023-10-25 00:49
Only work tracked with this epic so far is js-waku work: https://github.com/orgs/waku-org/projects/2/views/2?filterQuery=is%3Aopen+label%3A%22E%3A2.2%3A+Sharded+cap+discovery+for+light+protocols%22&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status

From https://github.com/waku-org/research/issues/3#issuecomment-1682623882

> Task: Service peer selection on specific shards
> 
> Currently a service peer (e.g. a store node) is either provided by the application or it expects the peer manager to suggest a suitable service peer (selectPeer()). This task focuses on the latter: peer manager should provide ability to find service peers for a specific shard, based on the content topic that the application is interested in (e.g. an API call to selectPeer(Protocol, ContentTopic)), or kick off an ad-hoc discovery process until a suitable service peer is found. Client APIs (for filter, lightpush, peer-exchange) should automatically make use of this mechanism if the application does not explicitly set the desired service peer.
> 
> Owners:
> 
>     Overall: @alrevuelta
>     Implementations:
>         nwaku: @alrevuelta
>         go-waku: @chaitanyaprem
>         js-waku: ??
> 
> Priority: critical for launch

I do not see any issue tracking this work in nwaku/research.go-waku.

@alrevuelta, are you able to clarify the work needed here? cc @jm-clius

**Comment by alrevuelta** [comment] 2023-10-25 09:02
https://github.com/waku-org/pm/issues/63#issuecomment-1778296008

@SionoiS Mind having a look? Maybe related to some of the peer management work you are doing?

**Comment by SionoiS** [comment] 2023-10-25 11:46
Duplicate of https://github.com/waku-org/nwaku/issues/1941???

**Comment by fryorcraken** [comment] 2023-10-30 06:14
> Duplicate of [waku-org/nwaku#1941](https://github.com/waku-org/nwaku/issues/1941)??? If not, can the difference be clarified?

I suggest to sync with @jm-clius

**Comment by jm-clius** [comment] 2023-10-30 17:16
@SionoiS not a duplicate afaics, but the nwaku issue should be linked in this Epic description. The Epic tracks work across all clients.

**Closed** 2024-02-03 05:50 UTC
Labels: Epic, E:2.2: Sharded cap discovery for light protocols
